POST http://localhost:3000/auth/register
Content-Type: application/json

{
  "name": "sascha",
  "email": "sascha@gmail.com",
  "password": "alexanderspassword" 
}

###

POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email": "sascha@gmail.com",
  "password": "alexanderspassword" 
}

###
POST http://localhost:3000/auth/token
Content-Type: application/json

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoyLCJpYXQiOjE1OTk4NjA4ODJ9.SpYHRJiK8ZIIG1cRifldoB_C1BqJvfDzaXwb4zJnYyM"
}

###

DELETE http://localhost:3000/auth/logout
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoyLCJpYXQiOjE1OTk4NjEyMDEsImV4cCI6MTU5OTg2MjEwMX0.JpNheQ_OBQIqSiJZ6Rlco-QNB_PFBdA90dTyS5FCpgA

###

GET http://localhost:3000/user

###

GET http://localhost:3000/user/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7InVzZXIiOjIsImlhdCI6MTU5OTg1NjI4OX0sImlhdCI6MTU5OTg1ODYwOSwiZXhwIjoxNTk5ODU4NjM5fQ.hbJ2QPBehmmzCZKPdi5-JmQVigfc1CawRq51KWwYE14

###

DELETE http://localhost:3000/user/1

###

PATCH http://localhost:3000/user/2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiaWF0IjoxNTk5NzgzNDIyfQ.I6cVp58EXeicksoA8rQzcsUs3LICIzNN9N3ZMWnSkNY
Content-Type: application/json

{
  "id": 3,
  "name": "alexander luna",
  "email": "sascha@gmail.com",
  "password": "alexanderspassword"
}

