POST http://localhost:3000/user/register
Content-Type: application/json

{
  "name": "alexander",
  "email": "alexander@gmail.com",
  "password": "alexanderspassword" 
}

###

POST http://localhost:3000/user/login
Content-Type: application/json

{
  "email": "alexander@gmail.com",
  "password": "alexanderspassword" 
}

###

GET http://localhost:3000/user

###

GET http://localhost:3000/user/5f593f811a031c22c3d31377
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Il9pZCI6IjVmNTkzZjgxMWEwMzFjMjJjM2QzMTM3NyIsIm5hbWUiOiJhbGV4YW5kZXIiLCJlbWFpbCI6ImFsZXhhbmRlckBnbWFpbC5jb20iLCJwYXNzd29yZCI6IiQyYiQxMCRUVHdNRlVSR21MR2Z5SFZTbUpZcy5lNjcwaERyeFppZkJuMXM5dDBwdjA4aGs3OVJYTm1VVyIsImNyZWF0ZWRBdCI6IjIwMjAtMDktMDlUMjA6NDg6MDEuNzA2WiIsIl9fdiI6MH0sImlhdCI6MTU5OTc0NTM3MX0.hBkU5ZtCGdQrE8yIIthgSglhHCcbca38Jub-pU_WZLU

###

DELETE http://localhost:3000/user/5f593f811a031c22c3d31377

###

PATCH http://localhost:3000/user/5f593f811a031c22c3d31377
Content-Type: application/json

{
  "name": "alexander luna"
}

